import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import { InterviewProvider } from "./context/InterviewContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex w-screen h-screen">
          <Sidebar />
          <div className="flex-1 overflow-auto">
            <InterviewProvider>
              {children}
            </InterviewProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
